# change the followings to match your Github username and repo name
baseurl: "/" # the name of your github repo
url: "https://blog.inboxairlock.com" # the url of your github pages

# site information used in page title, meta data etc.
title: "Inbox Airlock Blog"
description: Inbox management tips, thoughts on micro SaaS

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Inbox Airlock
author-bio: Keep your Gmail inbox clear from unwanted email
author-image: ia-logo.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: false

nav-menu:
- text: Main Website
  permalink: https://www.inboxairlock.com
- text: Blog
  permalink: /

# use false to turn off any social media links
twitter: https://twitter.com/inboxairlock
facebook: false
instagram: false
github: false
linkedin: https://www.linkedin.com/company/100113446
medium: false
google-scholar: false
email: hello@inboxairlock.com

# footer information
footer-msg: "Inbox Airlock - Keep your inbox clear from unwanted email"
footer-msg-link: https://www.inboxairlock.com

# google analytics
google-analytics: false

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
